services:
  postgres:
    image: postgres:16-alpine
    container_name: cyclo-ranking-db
    restart: always
    environment:
      POSTGRES_USER: cycloranking
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: cycloranking
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
